# variables:
#   branch_name: $[ coalesce(variables.branch_name_override, '', 'master') ]

trigger: none

pool:
  vmImage: ubuntu-latest

# resources:
#   repositories:
#   - repository: checkstyle
#     type: git
#     name: Sandpit-Glen
#     ref: $(branch_name)

jobs:
  - job: RunCheckStyle
    steps:
      # - checkout: checkstyle

      - task: Powershell@2
        displayName: Running checkstyle on src files
        inputs:
          targetType: 'inline'
          script: gradle clean check

      - task: PowerShell@2
        displayName: 'Creating zip file'
        inputs:
          targetType: 'inline'
          script: |
            $source = '$(Build.SourcesDirectory)\build\reports\checkstyle\main.html'
            $dest = '$(Common.TestResultsDirectory)\checkstyle.zip'
            Compress-Archive -Path $source -DestinationPath $dest
        continueOnError: true
        condition: always()

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Common.TestResultsDirectory)'
          artifact: 'checkstyle.zip'
          publishLocation: 'pipeline'
        continueOnError: true
        condition: always()